/*import java.lang.NumberFormatException;
public class Sum {
  public static void main(String[] args)  {
    String a="1+V";
    String b="1+1";

  /*  try {
      calc(a);
      //compute(1);
      //compute(20);
    } catch (MyExcept e) {
      System.out.println("Перехваченное исключение." + e);
    }
  }
*/

/*


    try {
      System.out.println(calc(a));

      System.out.println(calc(b));
    }
    catch (MyExcept e){ System.out.println("исключение");
    }

  }




  public static String calc(String inputString) throws  MyExcept{*/
   /* try {
      String [] a = inputString.split("\\+");
      Integer.parseInt(a[1]);
    }
    catch (ArrayIndexOutOfBoundsException e){ System.out.println("исключение");
    }

    String[] vmas = inputString.split("\\+");

    int a1 = 0, a2 = 0;
    String x="";
    a1 = Integer.parseInt((vmas[0]));

    a2 = Integer.parseInt(vmas[1]);

    int sum = a1 + a2;
    if (sum > 0) {x = x + sum;}

    return x;
  }
}

class MyExcept extends Exception {

  public MyExcept(String detail) {
    super(detail);
  }

  @Override
  public String toString() {
    return "MyException{"
            + "detail=" + ", message=" + getMessage()
            + "} ";
  }
}

*/